[versions]
gradle = "8.12"
kotlin = "2.0.21"

[libraries]
common = "com.android.tools:common:+"
sdklib = "com.android.tools:sdklib:+"
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.+"
jaxb-api = "jakarta.xml.bind:jakarta.xml.bind-api:2.3.+"
jaxb-runtime = "org.glassfish.jaxb:jaxb-runtime:2.3.+"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
