name: "Deploy"
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v28
      - name: update flake inputs
        run: |
          nix flake update
          git add flake.lock
      - name: update android sources
        run: ./scripts/update.sh
      - name: test
        run: |
          nix flake check --show-trace
          nix flake check ./nix-android-repo --show-trace
      - name: push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          ./scripts/deploy.sh
  channel:
    runs-on: ubuntu-latest
    needs: update
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v28
      - name: build nixexprs
        run: ./scripts/channel.sh
      - name: deploy nix channel
        uses: JamesIves/github-pages-deploy-action@4.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: pages-build
          single-commit: true
          git-config-name: "github-actions"
          git-config-email: "github-actions@github.com"
  sync:
    runs-on: ubuntu-latest
    needs: update
    strategy:
      matrix:
        channel: [stable, beta, preview, canary]
    steps:
      - name: main -> ${{ matrix.channel }}
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: main
          target_branch: ${{ matrix.channel }}
          github_token: ${{ github.token }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.channel }}
      - name: tag ${{ matrix.channel }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          tag="$(date --utc --iso-8601)-${{ matrix.channel }}"
          git tag --annotate --message "Version $tag" "$tag"
          git push origin "$tag"
